# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://ljk233.github.io/leetcode/"

git_url = "https://github.com/ljk233/leetcode/tree/main/"

def custom_doc_links(name): return None
